ALLOWED_ORIGINS=http://127.0.0.1:5500,http://localhost:5500
CASSANDRA_IP=172.31.9.25
CASSANDRA_PORT=9042
CASSANDRA_KEYSPACE=batch1_2026_trainees
GAMES_BY_ROOM_TABLE=leo_games_by_room
MOVES_BY_GAME_TABLE=leo_moves_by_game
GAMES_BY_PLAYER_TABLE=leo_games_by_player

